version: '3.9'

services:
  app1:
    build: ./app1
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SERVICE_NAME=Todo Service
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  app2:
    build: ./app2
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SERVICE_NAME=Weather Service
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SERVICE_NAME=API Gateway
    networks:
      - app-network
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge


