version: '3'

services:
  api1:
    build: ./api1
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development

  api2:
    build: ./api2
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
  
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - api1
      - api2