version: '3.9'

services:
  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SERVICE_NAME=Product Service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SERVICE_NAME=User Service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - SERVICE_NAME=Order Service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SERVICE_NAME=API Gateway
    depends_on:
      product-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 🔽 Hier fügst du deine neuen Services hinzu:

  api-1:
    build: ./chris_ibrahim/api-1
    ports:
      - "3101:3001"

  api-2:
    build: ./chris_ibrahim/api-2
    ports:
      - "3102:3002"

  chris-gateway:
    build: ./chris_ibrahim/gateway
    ports:
      - "3100:8080"
    depends_on:
      - api-1
      - api-2
