version: '3.9'

services:
  nico-service:
    build: ./nico
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SERVICE_NAME=User Service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 3