version: '3'
services:
  api1:
    build: ./api-1
    container_name: api1
    ports:
      - "3001:3001"

  api2:
    build: ./api-2
    container_name: api2
    ports:
      - "3002:3002"

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - api1
      - api2
