version: '3.9'

services:
  api_1:
    build: ./api_1
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SERVICE_NAME=Service_1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  api_2:
    build: ./api_2
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SERVICE_NAME=Service_2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  api-gateway:
    build: ./api_gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SERVICE_NAME=API Gateway
    depends_on:
      api_1:
        condition: service_healthy
      api_2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
